# Generated by Django 3.2.16 on 2024-02-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20240206_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
